#!/bin/sh

CORES=1

for d in 0.05 0.1 0.15 0.2 0.25 0.30 0.35 0.40
do
    POLE_LENGTH=$(bc <<<  $d*2.0)
    for (( c=1; c<=100; c++))
    do
        /usr/bin/time ./esp -h=5 -n=100 -b=15 -spl=$d 2>> ./runs/"runtime_{$POLE_LENGTH}_{$CORES}.csv" 1 | tail -1 >> ./runs/"convergence_{$POLE_LENGTH}_{$CORES}.csv"
        echo "run$c done -> $POLE_LENGTH short pole length -> $CORES core(s)"
    done
done
