#!/bin/sh

CORES="$1"

for d in 0.30 0.35 0.40 0.425
do
    POLE_LENGTH=$(bc <<<  $d*2.0)
    for (( c=1; c<=100; c++))
    do
        /usr/bin/time ./sane-parallel -h=5 -n=120 -cpus=$CORES -spl=$d 2>> ./runs/"runtime_{$POLE_LENGTH}_{$CORES}.csv" 1 | tail -1 >> ./runs/"convergence_{$POLE_LENGTH}_{$CORES}.csv"
        echo "run$c done -> $POLE_LENGTH short pole length -> $CORES core(s)"
    done
done